# Generated by Django 4.2.6 on 2024-01-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='blocker',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Ironing', 'Ironing')], default=[]),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='location_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='location_county',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
