# Generated by Django 4.2.6 on 2024-02-03 06:41

import django.core.validators
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraccount_blocker_useraccount_location_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='blocker',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Ironing', 'Ironing')], default=[], max_length=15, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
