# Generated by Django 4.2.6 on 2024-01-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraccount_blocker_useraccount_location_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='location_city',
            field=models.CharField(default='Indore', max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='location_county',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
