# Generated by Django 4.2.6 on 2024-01-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_useraccount_location_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='location_county',
            new_name='location_country',
        ),
    ]
