# Generated by Django 4.2.6 on 2024-02-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_useraccount_blocker'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='location_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
