# Generated by Django 4.2.6 on 2024-02-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_useraccount_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
