# Generated by Django 4.2.6 on 2024-02-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_useraccount_profile_picture_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
