# Generated by Django 4.2.6 on 2024-02-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='qr_picture',
            field=models.ImageField(blank=True, null=True, upload_to='qr_picture/'),
        ),
    ]
